name: unit_testing_repository_pattern
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  firebase_core: ^1.22.0
  cloud_firestore: ^3.4.8
  http: ^0.13.5
    
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true